In [ ]:
#####  MyDriveのマウント

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#####  方法1：ディレクトリ内のすべてのcsvファイル名を取得し、上位部分と結合する

import os

# パスの指定
path = '/content/drive/MyDrive/receipts/処理結果/csv'

# ファイル名のリストを取得
file_names = os.listdir(path)

# 取得したファイル名を表示
for file_name in file_names:
    print(file_name)

print()

# フルパスに変換
csv_paths = [os.path.join(path, f) for f in os.listdir(path)]  # 内包表記を利用
print(csv_paths)

202603061112 - 領収書一覧表の作成と確認.csv
202603061113 - ウェルファム関連経費の請求情報.csv
202603061115 - 請求情報検索 (1).csv

['/content/drive/MyDrive/receipts/処理結果/csv/202603061112 - 領収書一覧表の作成と確認.csv', '/content/drive/MyDrive/receipts/処理結果/csv/202603061113 - ウェルファム関連経費の請求情報.csv', '/content/drive/MyDrive/receipts/処理結果/csv/202603061115 - 請求情報検索 (1).csv']

In [ ]:
# #####  方法2：ディレクトリ内のすべてのcsvファイルをフルパスを直接取得する

# import glob

# path = '/content/drive/MyDrive/receipts/処理結果/csv/*.csv'
# csv_paths = glob.glob(path)

# print(csv_paths)

In [ ]:
#####  pandasで読み込んでみる

import pandas as pd

# 内容の確認
print(f"読み込んだファイル: {csv_paths[2]}")
# 先ほどのglobなどで取得したリストの1番目（インデックス0）を読み込む
df = pd.read_csv(csv_paths[2])

# 内容の確認
# print(f"読み込んだファイル: {csv_paths[1]}")
# display(df.head())

読み込んだファイル: /content/drive/MyDrive/receipts/処理結果/csv/202603061115 - 請求情報検索 (1).csv

In [ ]:
##### 複数のcsvを読み込んで結合する

# 各ファイルを読み込んでリストに格納
df_list = []
for path in csv_paths:
    temp_df = pd.read_csv(path)
    df_list.append(temp_df)

# すべてのDataFrameを縦方向に結合
df_concat = pd.concat(df_list, ignore_index=True)

# 結果の確認
print(f"結合したファイル数: {len(df_list)}")
print()
print(f"結合した領収書数: {len(df_concat)}")
print(len(df_concat))
print()

print('最初の3つ')
display(df_concat.head(3))
print()
print('最後の3つ')
display(df_concat.tail(3))

結合したファイル数: 3

結合した領収書数: 6
6

最初の3つ

,日付,請求元,電話番号,登録番号,種別,金額合計（税込）,消費税額
0,2025/10/08,株式会社 HERO innovation,不明,T6010001151703,通信費（メルプ問診）,"19,800","1,800"
1,2025/12/29,株式会社ファインデックス,不明,T9500001003380,支払手数料（署名サービス料）,"11,000","1,000"
2,2025/12/19,東日本旅客鉄道株式会社,不明,T9011001029597,旅費交通費,"12,160",不明

最後の3つ

,日付,請求元,電話番号,登録番号,種別,金額合計（税込）,消費税額
3,2025/12/20,株式会社ウェルファム,03-6263-8686,T1010001220454,接待交際費,"34,334",不明
4,2026/02/20,株式会社 長岡ガーデン,(0258) 32-1083,T5110001022993,消耗品費,"2,750",250
5,2025/12/29,株式会社ファインデックス,不明,T9500001003380,通信費,"11,000","1,000"

In [ ]:
#####  結合したdf_concatをcsvファイルとして保存する

# 保存先のディレクトリパス
output_dir = '/content/drive/MyDrive/receipts/処理結果/結合済みcsv'
file_name = 'test_concat.csv'

# 保存先のフルパスを作成
save_path = os.path.join(output_dir, file_name)

# CSVとして保存
# index=False にすることで、DataFrameのインデックス（左端の数字列）を除外して保存できます
df_concat.to_csv(save_path, index=False, encoding='utf-8-sig')

print(f"保存が完了しました: {save_path}")

In [7]:
var = 5
if var > 0:

    if var % 3 == 0 and var % 5 == 0:
        print ("FizzBuzz")
    elif var % 3 == 0:
        print ("Fizz")
    elif var % 5 == 0:
        print ("Buzz")
    else:
        print (var)

Buzz